### PR TITLE
Some initial proposed changes to the script file format

### PR DESCRIPTION
**Pull request by afishbeck**
Some of this is actual format changes, other parts would just be
considered best practices.

I don't want to require more layers than needed.  A transform can be
the only thing in the file, or a collection of transforms.

I think we can support the collection of transforms in the script
namespace whether or not the scripting engine is goint to be separating
them.

Signed-off-by: Anthony Fishbeck <anthony.fishbeck@lexisnexisrisk.com>

### CODE REVIEW

**Comment by afishbeck** [comment]
@asselitx @timothyklemm trying to keep the suggestions granular.  Please review.

**Review by timothyklemm — COMMENTED** [review]
I think both versions are overly simplistic. The original version is obviously based on the limited functionality that was available until this week, and the edited version stays within those limits.

One thing that should be done is to remove the hoops that were necessary to get anything done. SetValue, or set-value, no longer requires a when or otherwise as its parent. SetValue can now be used to define a value when you don't know if the full path to it exists. But that's just nitpicking.

We intend to apply strict validation rules when loading a configuration in the ESP. I think we should have strict validation when building the configuration. And I don't mean applying the ESP's load validation from within the builder.

1. To which of the 10 types of entry point does any single transform apply?
2. Put another way, in which of the 10 types of entry point is the use of a transform completely invalid?
3. How do we verify that a transform intended for use with one method in one service, possibly even bound to a specific esdl definition, is being used as intended?
4. How do we verify that a transform intended for use with a specific service, again possibly tied to a specific definition, is not being configured for an unrelated service?
5. I think we should provide a way to our script markup to "external" dependencies it has, and not just hope that things work out. Case in point, the request-response logging is currently implemented in native code by processing an xslt. We will need to be able to invoke an xslt from within a transform. A transform tied to a specific xslt should be able to be tightly coupled in the definition.

The only thing we can tell about a transform that resides by itself is that it can be used anywhere, anytime. There are far too many transforms for which that won't be true. The configuration loader will only be able to tell if the configuration is well-formed; only the builder will be able to tell if its valid, and only if it is given the context that this change made a point to remove.

My idea of global-module, service-module, and method-module was basically a contextual replacement for Terrence's Script element. The module element implies some amount of context, and that which can't be implied can be specified in the element definition. Modules would not have to be monolithic in the repo, the definition of one module could be split into multiple files with the ESP merging the selected pieces together when loading the configuration.

**Comment by afishbeck** [comment]
It's a low priority for me to turn the scripts into full examples at this point.  That will come later or someone else can jump in.
The scripts for me are there so I can understand organization and framework.
Agree it would be nice for the transforms to declare what they expect for the xml they will be working on.  Of course it's to prevent whoever is creating the binding and manifest from making a mistake so doesn't block us functionally.  And hopefully it doesn't get in the way of easily putting stuff together.. that is, "hey include this script in your ESDLrequest entry point,.. and modify the generic script that deals with Transaction ids so the script doesn't get rejected.  Probably need a way to say the script can be used anywhere... without at this stage having to add more complexity like categories or base types.

**Comment by asselitx** [comment]
@timothyklemm is right that these transforms (original versions and Tony's) are simplistic and outdated, but @afishbeck 's changes in this PR are useful to make it look like more _valid_ script even if it isn't _optimal_.

I think these changes are a good and necessary step.

Regarding Tim's questions 1-4: Validation is good, but I am concerned though that enforcing strict validation when building the configuration may be too heavyweight or complex, at least at first- until we can see that it would be beneficial. Also to some degree correct dependency markup relies on developer diligence similar to how choosing correct shared transforms does.

Regarding question 5, it would be good to have some way for a transform to indicate it needs to use some external script or xslt. Perhaps that is part of what the <include-from> does. Maybe it keys behavior off the extension of the included resource, or there is an attribute indicating resource type (defaulting to our script type if omitted)?

**Comment by timothyklemm** [comment]
Classifying something while writing can be beneficial to the author - it requires thought about the intended use of what's being written. If reclassification is necessary to use an existing item in place it wasn't originally intended, it should prompt extra attention to be paid to whether it was improperly classified initially or if there is a legitimate reason it can't be used as written.

Changing an implementation of something already available to you should done with extreme caution. If you're changing the behavior of something already in use, you need to consider whether your changes are such that the existing users should grow into them (eventually) or if you would be better off with a new entity.

My thought on distinguishing global from anything else is that anything else will be tied to (at least) one service and or service/method combination. The absence of that association would make it available to all.

And I did say my comment about the markup was nitpicking. I just found it amusing that the sample markup was as bad as it is.

**Review by asselitx — APPROVED** [review]
I'm ok with merging these changes. @timothyklemm ?
Once merged I'll mockup and push a proposal for dependency declaration on the transforms.

**Review by timothyklemm — APPROVED** [review]

**Pull request merged**
